# Generated by Django 4.0.10 on 2024-06-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
