# Generated by Django 5.0.6 on 2024-07-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descritpion',
            new_name='description',
        ),
    ]
