# Generated by Django 5.0.6 on 2024-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_rename_descritpion_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
