# Generated by Django 5.0.6 on 2024-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_alter_threat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
