# Generated by Django 5.0.6 on 2024-06-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_threat_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='threat',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.threatorigin'),
        ),
        migrations.AddField(
            model_name='threat',
            name='threat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.threattype'),
        ),
    ]
