# Generated by Django 5.0.6 on 2024-06-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_threatorigin_threattype_threat_origin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatorigin',
            old_name='name',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='threattype',
            old_name='name',
            new_name='type',
        ),
    ]
