# Generated by Django 5.0.6 on 2024-06-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_rename_name_threatorigin_origin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat',
            old_name='threat_type',
            new_name='type',
        ),
    ]
